# Generated by Django 4.0.6 on 2022-07-20 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articlescope_tag_remove_relationship_article_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlescope',
            options={'ordering': ['-is_main'], 'verbose_name': 'Тематический раздел', 'verbose_name_plural': 'Тематические разделы'},
        ),
    ]
