# Generated by Django 4.0.6 on 2022-07-20 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_articlescope_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тематический раздел', 'verbose_name_plural': 'Тематические разделы'},
        ),
    ]
