# Generated by Django 4.0.6 on 2022-07-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_article_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlescope',
            name='is_main',
            field=models.BooleanField(blank=None, default=False, verbose_name='Основной'),
        ),
    ]
